module.exports = {
    FB_PAGE_TOKEN: 'EAACTpI4U82YBAGF3qHH5AVP0uuZANwQFD863sPJZBntJVKojwMgGutqEQTIuZAEavYtpXATEZAiUt5QpxijHte2x0L1CrynXtNNjwAZCJG8Q8wUfsAK0CTZBkbISvc8jsZAL13ykgdDiZBjSDdVkCOp65DxVzp1f4ogTBEOplp9o5dZCGt2cejAzd',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};